version: "3"

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      rot:
        aliases:
          - db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  db_migrations:
    build:
      context: ..
      dockerfile: ./deployments/migrations/Dockerfile
    depends_on:
      - db
    networks:
      - rot

  mq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      rot:
        aliases:
          - mq
    ports:
      - '5672:5672'

  rotator:
    build:
      context: ..
      dockerfile: ./deployments/rotator/Dockerfile
    depends_on:
      - db_migrations
    restart: always
    networks:
      rot:
        aliases:
          - rotator
    ports:
      - '8888:8888'

  statistic:
    build:
      context: ..
      dockerfile: ./deployments/statistic/Dockerfile
    depends_on:
      - db_migrations
      - mq
    networks:
      rot:
        aliases:
          - statistic
    restart: always

volumes:
  dbdata:

networks:
  rot:
    external:
      name: rotator_network