version: '3'

services:
  integration-tests:
    build:
      context: ..
      dockerfile: ./deployments/tests/Dockerfile
    networks:
      rot:
        aliases:
          - db

networks:
  rot:
    external:
      name: rotator_network